### ISSUE TITLE
Rec'd an Error at Map Generation

### ISSUE THREAD

**Issue by abordoli** [sparr/factorio-mod-belt-overflow#6]
"
Attempting to call math.random() outside an event or during loading. This is invalid and will cause desyncs.
stack traceback:
	__belt-overflow__/control.lua:9: in main chunk
"

Regards,
~B

**Comment by abordoli** [comment]
Now receiving another error (but at game boot-up; not sure if the above error is happening as the game won't proceed that far do to this one) that I have troubleshot down to this mod by elimination of all others (basically, the error happens when the mod is toggled on, but doesn't when toggled off; everything else being equal)...

Here is the error:
Error
Sprite cropping failed. Captured bitmap data for sprite "__base__/graphics/entity/radar/radar.png" was null,

I actually saw another error prior that was related to a large biter.

I will investigate more and this seems to be a bug-mesh.

EDIT: I will report back as I investigate further as I feel more than one error from different mods is happening at once. I will correct the above error or remove this post if it was something else.

**Comment by sparr** [comment]
first crash fixed in 0.15.4

no idea how second problem could be related to this mod. if you can figure it out, open a new issue please.

**Comment by abordoli** [comment]
Thxs!
